version: '3'
services:
  node-server:
    build:
      context: ./Node
      dockerfile: Dockerfile
    ports:
      - 8080:3000
    depends_on:
      - postgres-db
  postgres-db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ourvol:/var/lib/postgresql/data
volumes:
  ourvol:
